### PR TITLE
deserialse to domain class rirght from the response

### PR DESCRIPTION
**Pull request by edewit**
@corinnekrych instead of the user doing it the sdk could do this.

### CODE REVIEW

**Comment by corinnekrych** [comment]
:eyes:

**Comment by danielpassos** [comment]
@edewit @corinnekrych Still valid?

**Comment by edewit** [comment]
yeah @danielpassos I think it's an nice addition instead of getting a list back with JsonObjects you get list of domain objects

**Comment by danielpassos** [comment]
Thanks @edewit I have merged it in https://github.com/feedhenry/fh-dotnet-sdk/commit/6b5b1c5b351386a396d3f0ba600ca7194d691ce4

**Pull request closed without merging**
