### PR TITLE
temp_id on update fix

### PR DESCRIPTION
**Pull request by edewit**
Part of [RHMAP-2528](https://issues.jboss.org/browse/RHMAP-2528)

This fix addresses the create -> update issue row 4 in spreadsheet

@wei-lee used js as a reference, but there is still one error the UidMapping will grow and because it's saved on the device it will crash the app eventually. Don't know when we can clear this list but we need to build this in as well.

### CODE REVIEW

**Comment by wei-lee** [comment]
looks good. Have you seen the app crashes because of the the UidMapping? What error did you get? Yeah, I am not sure about the best way to clear that map too.

**Comment by edewit** [comment]
@wei-lee haven't seen the app crash, but when it will continue to grow it will eventually take up either all the memory or all the disk space, right?

**Comment by wei-lee** [comment]
yeah. But in that case, the crash won't be caused by the UidMap, the whole dataset size will probably grow over the maximum memory that is allowed for an app on the device. It's one of the known limitations of the framework.

We can definitely look into improvements in the future.

**Comment by corinnekrych** [comment]
@edewit @wei-lee same story with the historyChange, like the uidmapping, this is temporary infomation that could be cleaned to minimize the size of the storage. let add a jira to track it.

**Comment by wei-lee** [comment]
history change should be removed. It's not required anymore?

We the others including meta data which will be clean update automatically after each sync loop. So the only data that will keep growing are the dataset and the uid map.

**Pull request merged**
