### PR TITLE
Update build

### PR DESCRIPTION
**Pull request by sedroche**

### CODE REVIEW

**Comment by sedroche** [comment]
Retest this please

**Comment by corinnekrych** [comment]
@sedroche try relaunch appveyor to get a green build

**Comment by corinnekrych** [comment]
@sedroche trying out your branch this is what I get:

```
{ Dist } FH-v1.3.9 » nuget pack FHSDK.nuspec -Symbols
Attempting to build package from 'FHSDK.nuspec'.
Successfully created package 'C:\Users\corinnekrych\work\fh-dotnet-sdk\Dist\FH.SDK.1.3.9.nupkg'.
Successfully created package 'C:\Users\corinnekrych\work\fh-dotnet-sdk\Dist\FH.SDK.1.3.9.symbols.nup 
```   
with NuGet Version: 3.4.3.855

**Comment by corinnekrych** [comment]
@sedroche this is what I get:
```
{ Dist } FH-v1.3.9 » nuget push FH.SDK.1.3.9.nupkg
Source parameter was not specified.
```
different from yours.
let me try to upload it

**Comment by corinnekrych** [comment]
@sedroche uploaded here:
https://www.nuget.org/packages/FH.SDK/1.3.9

**Pull request merged**
