### PR TITLE
Coverage

### PR DESCRIPTION
**Pull request by edewit**
Changed to use test that use mocks instead of running node server, target windows 8.1 and 8.0 xamarin ios and android

### CODE REVIEW

**Comment by corinnekrych** [comment]
@edewit :eyes:

**Comment by corinnekrych** [comment]
@edewit since Appveyor is using MS VS 12.0 maybe moving MSTestFramework to 12.0 will help getting rid of " Could not find SDK "MSTestFramework, Version=14.0"
see: https://github.com/feedhenry/fh-dotnet-sdk/pull/29
Let's see how the build goes...

I've also noticed that we have more warning on undocumented filed since you move them from private to public. maybe a separate PR to remove all warnings.

**Comment by corinnekrych** [comment]
@edewit no luck, i'm closing PR
we got this error now:
http://www.interact-sw.co.uk/iangblog/2014/04/23/wp81-msb3774

**Comment by edewit** [comment]
@corinnekrych your suggestion worked now it builds successful

**Comment by corinnekrych** [comment]
@edewit Just did a PR on your branch to remove some warnings.
+1 to merge.

**Comment by edewit** [comment]
what is wrong with the build?

**Comment by corinnekrych** [comment]
@edewit +1 to merge
there is still one or two missed documentation warning.

**Pull request merged**
