### PR TITLE
RHMAP-3581 Construct push url from host

### PR DESCRIPTION
**Pull request by edewit**
@corinnekrych could you have a look?

### CODE REVIEW

**Comment by matzew** [comment]
@edewit @corinnekrych any updates

**Comment by corinnekrych** [comment]
@matzew I'll review
@edewit any JIRA related to it?

**Comment by matzew** [comment]
@corinnekrych subject of the PR :-) 
RHMAP-3581

**Comment by corinnekrych** [comment]
+1

**Pull request merged**
