### PR TITLE
Fh 2701 override register

### PR DESCRIPTION
**Pull request by secondsun**
@edewit This fixes the registration bug I mentioned.  

To test this you need to install https://github.com/aerogear/aerogear-windows-push/pull/20 locally and build against it.

### CODE REVIEW

**Comment by edewit** [comment]
👍  let's release aerogear-windows to fix the build

**Comment by matzew** [comment]
@secondsun @edewit was this lib already released ?

**Comment by edewit** [comment]
@matzew yeah lib was released
@secondsun can you update the pr with the new lib?

**Comment by secondsun** [comment]
@edewit @matzew trying to :)  We are working out packaging issues

Summers Pittman
>>Phone:404 941 4698
>>Java is my crack.

**Pull request merged**
